### PR TITLE
GH-513 fix: Support custom field names for Milvus VectorStore collection

### LINKED ISSUE #513: The SDK of the vector database is very inflexible, unable to modify some database fields.
In the current version, taking the Milvus database as an example, I cannot specify the field names of the database collection. If I have a previously used collection, and if the fields do not match the current fixed fields, I cannot perform a query. I strongly suggest that custom field names should be allowed!!!

        public static final String DOC_ID_FIELD_NAME = "doc_id";

	public static final String CONTENT_FIELD_NAME = "content";

	public static final String METADATA_FIELD_NAME = "metadata";

	public static final String EMBEDDING_FIELD_NAME = "embedding";

### PR DESCRIPTION
**Pull request by ilayaperumalg**
- Add configuration properties to override the default field names for doc_id, content, metadata and embedding
- Add support to allow auto-id when enabled
- Add tests

Resolves #513

### CODE REVIEW

File: vector-stores/spring-ai-milvus-store/src/test/java/org/springframework/ai/vectorstore/MilvusVectorStoreCustomFieldNamesIT.java [hunk 1]
```diff
@@ -0,0 +1,259 @@
...
+import java.util.Map;
+
+import static org.assertj.core.api.Assertions.assertThat;
+
+/**
+ * @author Ilayaperumal Gopinathan
+ */
+@Testcontainers
+@EnabledIfEnvironmentVariable(named = "OPENAI_API_KEY", matches = ".+")
+public class MilvusVectorStoreCustomFieldNamesIT {
```
Comment (sobychacko) [inline vector-stores/spring-ai-milvus-store/src/test/java/org/springframework/ai/vectorstore/MilvusVectorStoreCustomFieldNamesIT.java:54]: We can drop the `public` modifier and keep it at default access.

File: vector-stores/spring-ai-milvus-store/src/test/java/org/springframework/ai/vectorstore/MilvusVectorStoreCustomFieldNamesIT.java [hunk 2]
```diff
@@ -0,0 +1,259 @@
...
+	}
+
+	private void resetCollection(VectorStore vectorStore) {
+		((MilvusVectorStore) vectorStore).dropCollection();
+		((MilvusVectorStore) vectorStore).createCollection();
+	}
+
+	@ParameterizedTest(name = "{0} : {displayName} ")
+	@ValueSource(strings = { "COSINE" })
+	public void searchWithCustomFieldNames(String metricType) {
```
Comment (sobychacko) [inline vector-stores/spring-ai-milvus-store/src/test/java/org/springframework/ai/vectorstore/MilvusVectorStoreCustomFieldNamesIT.java:84]: No need for `public`.

File: vector-stores/spring-ai-milvus-store/src/test/java/org/springframework/ai/vectorstore/MilvusVectorStoreCustomFieldNamesIT.java [hunk 3]
```diff
@@ -0,0 +1,259 @@
...
+				assertThat(resultDoc.getContent()).contains(
+						"Spring AI provides abstractions that serve as the foundation for developing AI applications.");
+				assertThat(resultDoc.getMetadata()).containsKeys("meta1", "distance");
+
+			});
+	}
+
+	@ParameterizedTest(name = "{0} : {displayName} ")
+	@ValueSource(strings = { "COSINE" })
+	public void searchWithoutMetadataFieldOverride(String metricType) {
```
Comment (sobychacko) [inline vector-stores/spring-ai-milvus-store/src/test/java/org/springframework/ai/vectorstore/MilvusVectorStoreCustomFieldNamesIT.java:125]: No need for `public`.

File: vector-stores/spring-ai-milvus-store/src/test/java/org/springframework/ai/vectorstore/MilvusVectorStoreCustomFieldNamesIT.java [hunk 4]
```diff
@@ -0,0 +1,259 @@
...
+				assertThat(resultDoc.getContent()).contains(
+						"Spring AI provides abstractions that serve as the foundation for developing AI applications.");
+				assertThat(resultDoc.getMetadata()).containsKeys("meta1", "distance");
+
+			});
+	}
+
+	@ParameterizedTest(name = "{0} : {displayName} ")
+	@ValueSource(strings = { "COSINE" })
+	public void searchWithAutoIdEnabled(String metricType) {
```
Comment (sobychacko) [inline vector-stores/spring-ai-milvus-store/src/test/java/org/springframework/ai/vectorstore/MilvusVectorStoreCustomFieldNamesIT.java:165]: no need for `public`.

File: vector-stores/spring-ai-milvus-store/src/test/java/org/springframework/ai/vectorstore/MilvusVectorStoreCustomFieldNamesIT.java [hunk 5]
```diff
@@ -0,0 +1,259 @@
...
+				assertThat(resultDoc.getContent()).contains(
+						"Spring AI provides abstractions that serve as the foundation for developing AI applications.");
+				assertThat(resultDoc.getMetadata()).containsKeys("meta1", "distance");
+
+			});
+	}
+
+	@SpringBootConfiguration
+	@EnableAutoConfiguration(exclude = { DataSourceAutoConfiguration.class })
+	public static class TestApplication {
```
Comment (sobychacko) [inline vector-stores/spring-ai-milvus-store/src/test/java/org/springframework/ai/vectorstore/MilvusVectorStoreCustomFieldNamesIT.java:208]: no need for `public`.

File: vector-stores/spring-ai-milvus-store/src/test/java/org/springframework/ai/vectorstore/MilvusVectorStoreCustomFieldNamesIT.java [hunk 6]
```diff
@@ -0,0 +1,259 @@
...
+		private String contentFieldName;
+
+		@Value("${test.spring.ai.vectorstore.milvus.embeddingFieldName}")
+		private String embeddingFieldName;
+
+		@Value("${test.spring.ai.vectorstore.milvus.metadataFieldName:metadata}")
+		private String metadataFieldName;
+
+		@Bean
+		public VectorStore vectorStore(MilvusServiceClient milvusClient, EmbeddingModel embeddingModel) {
```
Comment (sobychacko) [inline vector-stores/spring-ai-milvus-store/src/test/java/org/springframework/ai/vectorstore/MilvusVectorStoreCustomFieldNamesIT.java:229]: no need for `public`.

File: vector-stores/spring-ai-milvus-store/src/test/java/org/springframework/ai/vectorstore/MilvusVectorStoreCustomFieldNamesIT.java [hunk 7]
```diff
@@ -0,0 +1,259 @@
...
+				.withAutoId(isAutoId)
+				.withContentFieldName(contentFieldName)
+				.withEmbeddingFieldName(embeddingFieldName)
+				.withMetadataFieldName(metadataFieldName)
+				.build();
+			return new MilvusVectorStore(milvusClient, embeddingModel, config, true, new TokenCountBatchingStrategy());
+		}
+
+		@Bean
+		public MilvusServiceClient milvusClient() {
```
Comment (sobychacko) [inline vector-stores/spring-ai-milvus-store/src/test/java/org/springframework/ai/vectorstore/MilvusVectorStoreCustomFieldNamesIT.java:245]: no need for `public`.

File: vector-stores/spring-ai-milvus-store/src/test/java/org/springframework/ai/vectorstore/MilvusVectorStoreCustomFieldNamesIT.java [hunk 8]
```diff
@@ -0,0 +1,259 @@
...
+			return new MilvusServiceClient(ConnectParam.newBuilder()
+				.withAuthorization("minioadmin", "minioadmin")
+				.withUri(milvusContainer.getEndpoint())
+				.build());
+		}
+
+		@Bean
+		public EmbeddingModel embeddingModel() {
```
Comment (sobychacko) [inline vector-stores/spring-ai-milvus-store/src/test/java/org/springframework/ai/vectorstore/MilvusVectorStoreCustomFieldNamesIT.java:253]: no need for `public`.

File: spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/vectorstore/milvus/MilvusVectorStoreAutoConfigurationIT.java [hunk 9]
```diff
@@ -109,6 +109,57 @@ public void addAndSearch() {
 			});
 	}
 
+	@Test
+	public void searchWithCustomFields() {
```
Comment (sobychacko) [inline spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/vectorstore/milvus/MilvusVectorStoreAutoConfigurationIT.java:113]: Author tag needs to be updated for this class.

**Review by sobychacko — CHANGES_REQUESTED** [review]
